### PR TITLE
Add Interpretation class and refactor some existing interpretations

### PR DESCRIPTION
**Pull request by eb8680**
pair coded with @fritzo 

This refactors interpretations to be first-class objects, instances of subclasses of a base `Interpretation` class. Interpretations can be used directly as context managers and decorators. Most interpretation classes and objects have been moved to the new file `funsor.interpretations`; of the remaining interpretations, @fritzo would like to move the remaining `Memoize` and `MonteCarlo` into this file in a future PR, but others may stay where they are (`Substitute`, `AdjointTape`, `Optimize`).

## Proposed interface changes

| Old | New |
| ---: | :--- |
| `with interpretation(eager): ...` | `with eager: ...` |
| `@interpretation(eager)` | `@eager` |
| `eager(cls, *args)` | `eager.interpret(cls, *args)` |
| `@dispatched_interpretation` | `@DispatchedInterpretation` |
| `from funsor.terms import eager` | `from funsor.interpretations import eager` |

## Tests to fix

- [x] test/examples/test_bart.py::test_bart[monte-carlo-kl]
- [x] test/pyroapi/test_pyroapi.py::test_nested_plate_plate_ok[jit]
- [x] test/test_minipyro.py::test_nested_plate_plate_ok[funsor-py]
- [x] test/test_minipyro.py::test_nested_plate_plate_ok[funsor-jit]

### CODE REVIEW

**Comment by fritzo** [comment]
WDYT of getting some of this merged on Monday so we have more `memoize` machinery for tape-free transpose? #446

**Comment by eb8680** [comment]
Sure, although I don't think we should let it end up blocking anything

**Comment by fritzo** [comment]
@eb8680 mind if i work on getting this merged?

**Comment by eb8680** [comment]
Sure, go for it. You might want to focus on `DispatchedInterpretation` and `PrioritizedInterpretation` to begin with, and leave other interpretations (e.g. `Memoize`) to future PRs.

**Review by fritzo — APPROVED** [review]

**Pull request merged**
