### PR TITLE
Add DirichletCategorical conjugacy

### PR DESCRIPTION
**Pull request by fehiepsi**
by converting Categorical to Multinomial. Still no plate is supported yet.

### CODE REVIEW

**Comment by fritzo** [comment]
any idea why tests are failing?

**Comment by fehiepsi** [comment]
It is really strange. In my system, it even passes when I decreased the precision to 1e-7 or 1e-8. My only guess is due to some inconsistent behavior of JAX on travis...

**Comment by fehiepsi** [comment]
@fritzo I added numerical tests for conjugacy. They will verify if backend implementations are correct. In addition, we can test some pairs that are not avaiable in backends such as GammaGamma.

**Review by fritzo — APPROVED** [review]
Thanks for adding stronger tests!

**Comment by fehiepsi** [comment]
Thanks for reviewing! This is my first time to actual "use" Integrate and reduce stuffs. They are pretty convenient! Only one comment is arg names such as log_measure is a bit abstract. I know some usage cases of Integrate but can't figure what log measure means. :D

**Pull request merged**
