### PR TITLE
Rerun new version of black on the repo

### PR DESCRIPTION
**Pull request by ordabayevy**

### CODE REVIEW

**Review by fehiepsi — APPROVED** [review]

**Comment by ordabayevy** [comment]
Dropped Python 3.7 in jax tests

**Comment by fehiepsi** [comment]
I'm not sure how to remove jax 3.7 check. It seems that the master branch is protected. I also faced this issue in #600.

@fritzo Do you know some settings that allow us to merge this PR? I think one is under "Require status checks to pass before merging." check in the section ["Creating a branch protection rule"](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#creating-a-branch-protection-rule) I don't have access to the setting page so not sure if it works.

**Comment by fritzo** [comment]
@fehiepsi I've given you admin access.
@ordabayevy I've given you maintainer access.

@fehiepsi I don't understand why the jax 3.7 stage is unreported.  In the past when I've seen unexplainable unhelpful failures like this I have temporarily disabled "required checks", merged, then re-enabled checks.  Feel free to do so for this PR, or let me know if you'd like me to do it.

**Comment by fehiepsi** [comment]
Thanks Fritz. It turns out that `jax (3.7)` belongs to one of "Status checks that are required." I just updated it to `jax (3.8)`.

**Pull request merged**
