### PR TITLE
Add named_tensor_notation_i tutorial to index file

### PR DESCRIPTION
**Pull request by ordabayevy**
Run `make docs`, <s>looks fine</s>.

Actually, some latex code is not displayed. Investigating ...

### CODE REVIEW

**Comment by ordabayevy** [comment]
Some latex code were `$$ .. $$` missing and were not displayed in html after running `make docs`. Now it should be displayed correctly.

**Review by fritzo — APPROVED** [review]

**Comment by fehiepsi** [comment]
https://funsor.pyro.ai/en/latest/tutorials/named_tensor_notation_i.html here it goes

**Comment by fritzo** [comment]
I guess for the colab notebook to work, we would need a `!pip install funsor['torch']` at the top?  @fehiepsi how do you deal with installation in NumPyro?

**Comment by fehiepsi** [comment]
I guess we can add
```
!pip install funsor[torch]@git+https://github.com/pyro-ppl/funsor
```
to the top of the notebook. Currently, numpyro also suffers from the same issue (even worse, numpyro changes colab default devices gpu/tpu to cpu).

**Pull request merged**
