### PR TITLE
Bump to version 0.4.4

### PR DESCRIPTION
**Pull request by fehiepsi**
This is required for a breaking change in jax 0.4 which introduces `jax.Array`.

### CODE REVIEW

**Review by fritzo — APPROVED** [review]
LGTM, but looks like there's a new precision error?

**Comment by fehiepsi** [comment]
@fritzo Thanks for taking a look. I added a couple of changes for numerical issues and docs build (currently our doc build is still failing).

**Comment by fritzo** [comment]
@fehiepsi do you want me to publish this release, or do you want to do it?

**Comment by fehiepsi** [comment]
It seems the docs built successfully. I can make release after dinner

**Pull request merged**
