### PR TITLE
Named tensor notation tutorial Part 1

### PR DESCRIPTION
**Pull request by ordabayevy**
This is part 1 in the series of tutorials based on [Named Tensor Notation](https://namedtensor.github.io/). Any suggestions & corrections are very welcome.

[Link to the tutorial](https://nbviewer.jupyter.org/github/ordabayevy/funsor/blob/named-tensor-i/tutorials/named_tensor_notation_i.ipynb)

### CODE REVIEW

**Review by fritzo — COMMENTED** [review]
Looks great!  Thanks for splitting into smaller parts.

- [ ] Credit @davidweichiang, @srush, @boazbk by name after first link:
  `Named Tensor Notation (Chiang, Rush, Barak 2021)`
- [ ] nit: replace `torch.tensor` -> `tensor` everywhere for consistency.
- [ ] nit: you might simply write `.reduce(ops.add, "height")` rather than the verbose `.reduce(ops.add, reduced_vars="height")`; we use the terser notation in the funsor codebase.
- [ ] nit: consider adding equal signs to comments, e.g.
  ```py
  # A.sigmoid() =
  # ops.sigmoid(A) =
  # 1 / (1 + ops.exp(-A)) =
  1 / (1 + (-A).exp())
  ```
- [ ] Re: "TODO need help with reshaping", what can we help you with here?  You may be able to adapt some of the logic in the [flatten](https://github.com/pyro-ppl/funsor/blob/d5574988665dd822ec64e41f2b54b9dc929959dc/test/test_factory.py#L52) and [unflatten](https://github.com/pyro-ppl/funsor/blob/d5574988665dd822ec64e41f2b54b9dc929959dc/test/test_factory.py#L76) tests.
- note to self: it looks like we could simplify printing of `Bint[3, ]` -> `Bint[3]` and `Tensor(..., 'real')` -> `Tensor(...)`, but that is outside of this PR's scope.

**Comment by fritzo** [comment]
(Note we use `awaiting review`when the PR author is waiting on reviewers and `awaiting response` when reviewers are waiting on the PR author)

**Comment by ordabayevy** [comment]
Thanks for your feedback @fritzo! After  #511 gets merged I will re-run the cells to get better outputs.

**Review by fritzo — APPROVED** [review]

**Comment by srush** [comment]
This is really cool! Let us know if you had any issues with the doc or any suggestions about how to update it. We'll add a link in our next version update.

**Comment by fritzo** [comment]
@fehiepsi do you know how we can get this to show up on funsor.pyro.ai?  It would be nice to copy the setup you have in NumPyro.

**Comment by fehiepsi** [comment]
@ordabayevy @fritzo You can simply add `tutorials/[filename_without_.ipynb]` to this [index file](https://github.com/pyro-ppl/funsor/blob/master/docs/source/index.rst)

**Pull request merged**
